import { categoryById } from './categories.js';

// Broad, high-search-volume tags the platform adds to every Short.
const HIGH_VOLUME_TAGS = [
  'shorts', 'drawing', 'speed drawing', 'satisfying', 'art', 'digital art', 'satisfying video', 'relaxing',
  'aesthetic', 'animation', 'trending', 'viral shorts', 'shorts video', 'art shorts',
];

const YT_TAG_LIMIT = 480; // YouTube caps tags at 500 chars total (spaced tags count their quotes)
const pick = (list) => list[Math.floor(Math.random() * list.length)];
const hashtag = (tag) => '#' + tag.replace(/[^\p{L}\p{N}]/gu, '').toLowerCase();

function normalizeTags(tags) {
  const seen = new Set();
  const out = [];
  let used = 0;
  for (const raw of tags) {
    const tag = String(raw).replace(/^#/, '').replace(/[<>,]/g, '').trim().slice(0, 60);
    const key = tag.toLowerCase();
    if (!tag || seen.has(key)) continue;
    const cost = tag.length + (tag.includes(' ') ? 2 : 0) + (out.length ? 1 : 0);
    if (used + cost > YT_TAG_LIMIT) break;
    seen.add(key);
    out.push(tag);
    used += cost;
  }
  return out;
}

export function buildMetadata({ category, palette, userTags = [], footer = '' }) {
  // Shorts made with a style that has since been removed fall back to plain drawing metadata.
  const cat = categoryById[category] || { name: 'Drawing', titles: ['Satisfying Drawing'], hashtags: ['drawing', 'art'], description: 'A drawing made by code.' };
  const generic = [
    `${cat.name} Drawing`,
    `Satisfying ${cat.name} Art`,
    `Watch This ${cat.name} Come to Life`,
    `${cat.name}, Drawn by Code`,
  ];
  const title = `${pick([...cat.titles, ...generic])} #shorts`.slice(0, 100);

  // User tags come first so they survive the length cap.
  const tags = normalizeTags([...userTags, ...cat.hashtags, ...HIGH_VOLUME_TAGS]);

  const hashtags = [
    ...new Set(['#shorts', '#art', hashtag(cat.hashtags[1] || cat.hashtags[0]), ...userTags.slice(0, 5).map(hashtag),
      '#satisfying']),
  ].filter((h) => h.length > 1).slice(0, 12);

  const description = [
    `${cat.description} Every line, color and motion in this drawing is generated by code, so no two videos are the same.`,
    '',
    palette ? `Palette: ${palette}` : null,
    'Follow for a new drawing every day.',
    footer ? `\n${footer}` : null,
    '',
    hashtags.join(' '),
  ]
    .filter((l) => l !== null)
    .join('\n')
    .slice(0, 4900);

  return { title, description, tags };
}
